<?php
$consultation = $this->consultation;


$date = new DateTime();
?>
<div class="container">

       <div class="row">
           <div class="col-md-12">


               <h2><?= $consultation->getTitle() ?> - <?= $consultation->getCreatedDate()->format('d-m-Y') ?></h2>

               <p>
                   <?= $consultation->getDescription() ?>
               </p>



           </div>
       </div>

</div>