<?php

$listPatient = $this->listPatients;

?>

    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <h5>Liste des patients</h5>

                <form method="post"
                      action="<?= $this->url('patient/default', ['controller' => 'list', 'action' => 'addtolist']) ?>"
                      class="form-horizontal">
                    <p>Verifier s'il existe dans la base de données</p>

                    <div class="row">
                        <div class="col-md-4">
                            <input name="patientId" id="patientId" type="hidden" value="">
                            <input id="search" type="text" class="form-control typeahead" id="name"
                                   placeholder="Nom Patient ">
                        </div>
                        <div class="col-md-2">
                            <button type="submit" class="btn btn-primary btn-block">Ajouter a la liste</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <?php if ($this->errorUserExist): ?>
            <div class="alert alert-error">
                Patient exist dans la file
            </div>
        <?php endif; ?>
        <hr>

        <div class="gap"></div>
        <div class="row">
            <div class="col-md-6">
                <!-- Trends widget -->
                <div class="pm-widget">
                    <div class="pm-sidebar-padding">
                        <ul class="pm-trends-list">
                            <?php foreach ($listPatient as $queueRow): ?>
                                <li>
                                    <div class="row">
                                        <div class="col-md-8">
                                            <p>
                                                <?= $queueRow->getPatient()->getLastname(); ?>
                                                <?= $queueRow->getPatient()->getFirstname(); ?>
                                            </p>
                                        </div>
                                        <div class="col-md-4 text-right">
                                            <a href="<?= $this->url('patient/default',['controller'=>'patient-detail'])?>?patientId=<?= $queueRow->getPatient()->getId()?>"
                                               class="btn btn-info pop-btn">
                                                detail
                                            </a>
                                            <a href="<?= $this->url('patient/default',['controller'=>'list', 'action'=>'addtolist'])?>?action=remove&rowId=<?= $queueRow->getId()?>"
                                               class="btn btn-danger">&times;</a>
                                        </div>
                                    </div>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
                <!-- Trends widget end -->
            </div>
            <div class="col-md-6">
                <p>Nombre de patient en attente aujourd'hui <span>(<?= $this->nbrWaiting ?>)</span></p>

                <p>Nombre de patient traiter aujourd'hui <span>(<?= $this->nbrTreated ?>)</span></p>
            </div>
        </div>
    </div>

<?php $this->inlineScript()->captureStart();
echo <<<JS
 var names = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('lastname'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        remote: {
            url: '/patient/list/ajaxlist?q=%QUERY',
            wildcard: '%QUERY'
        }
    });
    $('#search').typeahead(null, {
        name: '',
        display: 'lastname',
        source: names,
        templates: {
            empty: [
                '<div class="empty-message">',
                'aucun nom correspand',
                '</div>'
            ].join(' '),
            suggestion: function(data) {
              //  console.log(data);
                return '<div class="tt-suggestion"><strong>' + data.lastname + '</strong> – ' + data.firstname + '</div>';
            }
        }
    });
    $('#search').bind('typeahead:select', function(event, data) {

        $('#patientId').val(data.id);
        console.log(data);
    }).bind('typeahead:open', function (event, data) {
        $('.tt-hint').css('background', ' url("/img/ajax-loader.gif") no-repeat center right');
    }).bind('typeahead:close', function (event, data) {
        $('.tt-hint').css('background-image', '');
    });


    $('a.pop-btn').colorbox();

JS;

$this->inlineScript()->captureEnd();
?>