<div class="wrap">
    <div class="row">
				
				<!--- Content -->
				<div class="full-width content textongrey">
					<h2>Send us a message</h2>
					<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit. All fields are required.</p>
				</div>
				<!--- //Content -->
				
				<!-- Form -->
				<div class="three-fourth">
					<!-- <form method="post" action="http://themeenergy.com/themes/html/transfers/contact_form_message.php" name="contactform" id="contactform"> -->
					<?php 
					
					$this->headTitle("Help");
					
					$form = $this->form;
					$actionURL = $this->url('contact', ['controller'=>'index', 'action'=>'index']);
					$form->setAttribute('action', $actionURL);
					
					$form->prepare();
					
					echo $this->form()->openTag($form);
					
					?>
						<div id="message"></div>
						<div class="f-row">
							<div class="one-half">
								<label for="name">Name and surname</label>
								<?php echo $this->formelement($form->get('name'));?>
								<?php echo $this->formelementerrors($form->get('name'));?>
							</div>
							<div class="one-half">
								<label for="email">Email address</label>
								<?php echo $this->formelement($form->get('email'));?>
								<?php echo $this->formelementerrors($form->get('email'));?>
							</div>
						</div>
						<div class="f-row">
							<div class="full-width">
								<label for="comments">Message</label>
								<?php echo $this->formelement($form->get('message'));?>
								<?php echo $this->formelementerrors($form->get('message'));?>
							</div>
						</div>
						<div class="f-row">
							<input type="submit" value="Submit" id="submit" name="submit" class="btn color medium right" />
						</div>
					</form>
				</div>
				<!-- //Form -->
				
				<!--- Sidebar -->
				<aside class="one-fourth sidebar right">
					<!-- Widget -->
					<div class="widget">
						<h4>Need help booking?</h4>
						<div class="textwidget">
							<p>Call our customer services team on the number below to speak to one of our advisors who will help you with all of your needs.</p>
							<p class="contact-data"><span class="ico phone black"></span> +1 555 555 555</p>
						</div>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Advertisment</h4>
						<a href="#"><img src="images/uploads/advertisment.jpg" alt="" /></a>
					</div>
					<!-- //Widget -->
				</aside>
				<!--- //Sidebar -->
			</div>
    </div>