<?php

/**
 * Generated by ZF2ModuleCreator
 */

namespace Board;


use Common\View\Helper\LayoutHelper;
use Zend\ModuleManager\Feature\AutoloaderProviderInterface;
use Zend\ModuleManager\Feature\ConfigProviderInterface;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;

class Module implements AutoloaderProviderInterface, ConfigProviderInterface
{

    /**
     * Returns configuration to merge with application configuration
     *
     * @return array|\Traversable
     */
    public function getConfig()
    {
        return include __DIR__ . '/config/module.config.php';
    }

    /**
     * Return an array for passing to Zend\Loader\AutoloaderFactory.
     *
     * @return array
     */
    public function getAutoloaderConfig()
    {
        return [
            'Zend\Loader\StandardAutoloader' => [
                'namespaces' => [
                    // Autoload all classes from namespace 'Board' from '/module/Board/src/Board'
                    __NAMESPACE__ => __DIR__ . '/src/' . __NAMESPACE__,
                ]
            ]
        ];
    }

    /**
     * @param MvcEvent $e
     */
    public function onBootstrap(MvcEvent $e){
        $app = $e->getApplication();
        $app->getEventManager()->attach(MvcEvent::EVENT_DISPATCH,  [$this, 'setLayout']);
    }


    /**
     * set different layout for specific routes
     *
     * @param MvcEvent $e
     */
    public function setLayout(MvcEvent  $e){
        $matchRoute = $e->getRouteMatch();
        $routeName = $matchRoute->getMatchedRouteName();
        $Routes  = explode('/', $routeName);
        $controller = $e->getTarget();

        $motherRoute = $Routes[0];
        if($motherRoute == 'board'){
            $boardView = new ViewModel();
            $boardView->setTemplate('layout/board');
            //add board layout to min layout
            $layout = $controller->layout();
            $layout->addChild($boardView, 'board');
        }


        $e->getApplication()->getServiceManager()
            ->get('viewhelpermanager')
            ->setFactory('layoutHelper',function($sm) use ($e) {
                $viewHelper = new LayoutHelper($e->getRouteMatch());
                return $viewHelper;
        });


    }




}