<?php

$patient = $this->patient;

?>

<div class="container">

    <div class="row">

    </div>

    <?php if ($patient): ?>
        <div class="gap"></div>
        <div class="row">
            <div class="col-md-6">
                <h5>Information du Malade </h5>
                <table class="table">
                    <tr>
                        <td>Nom</td>
                        <td><?= $patient->getLastname() ?></td>
                    </tr>

                    <tr>
                        <td>Prenom</td>
                        <td><?= $patient->getFirstname() ?></td>
                    </tr>

                    <tr>
                        <td>Sex</td>
                        <td><?= $patient->getGenderByName() ?></td>
                    </tr>

                    <tr>
                        <td>Année de naissance</td>
                        <td><?= $patient->getBirthYear() ?></td>
                    </tr>
                </table>
            </div>

            <div class="col-md-6">
                <h5>Consultations </h5>


            </div>
        </div>
    <?php else: ?>
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-warning">Aucun patient en attente </div>
            </div>
        </div>
    <?php endif; ?>

</div>

