<div class="container">

    <div class="row">
        <h5>Liste des patients</h5>

        <form class="form-horizontal">
            <p>Verifier s'il existe dans la base de données</p>
            <div class="col-md-4">
                <input type="text" class="form-control" id="name" placeholder="Nom Patient ">
            </div>
            <div class="col-md-2">
                <button type="submit" class="btn btn-primary btn-block">Ajouter a la liste</button>
            </div>
        </form>
    </div>

    <div class="gap"></div>
    <div class="row">
        <div class="col-md-6">
            <!-- Trends widget -->
            <div class="pm-widget">
                <div class="pm-sidebar-padding">
                    <ul class="pm-trends-list">
                        <li><a href="#">Majority of weight loss occurs 'via breathing'</a></li>
                        <li><a href="#">Majority of weight loss occurs 'via breathing'</a></li>
                    </ul>
                </div>
            </div>
            <!-- Trends widget end -->
        </div>
    </div>

</div>

