<?php
$patient = $this->patient;
$consulations = $patient != null ? $patient->getConsultations() : null;

$form = $this->form;
$form->setAttributes([
    'action'=>$this->url('patient/default', ['controller'=>'new-consultation']),
    'method'=>'post',
]);

$form->prepare();


?>

<div class="container">

    <div class="row">
    </div>

    <?php if ($patient): ?>
        <div class="gap"></div>
        <div class="row">
            <div class="col-md-6">
                <h5>Information du Malade </h5>
                <table class="table">
                    <tr>
                        <td>Nom</td>
                        <td><?= $patient->getLastname() ?></td>
                    </tr>

                    <tr>
                        <td>Prenom</td>
                        <td><?= $patient->getFirstname() ?></td>
                    </tr>

                    <tr>
                        <td>Sex</td>
                        <td><?= $patient->getGenderByName() ?></td>
                    </tr>

                    <tr>
                        <td>Année de naissance</td>
                        <td><?= $patient->getBirthYear() ?></td>
                    </tr>
                </table>
            </div>

            <div class="col-md-6">
                <h5>Consultations </h5>
                <?php if ($consulations->count() > 0): ?>
                    <table class="table">
                        <thead>
                        <tr>
                            <td>Date de consultation</td>
                            <td>Titre</td>
                            <td>Remarque</td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($consulations as $consultation): ?>
                            <tr>
                                <td><?= $consulation->getCreatedDate() ?></td>
                                <td><?= $consulation->getTitle() ?></td>
                                <td><?= $consulation->getDescription() ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php else: ?>
                    <div class="alert alert-info">
                        <p>Pas de consultation precedentes !</p>
                    </div>
                <?php endif; ?>

            </div>
        </div>

        <!-- consultation -->
        <div class="row">
            <div class="col-md-12">
                <h3>Nouvelle Consultation</h3>
                <?= $this->form()->openTag($form)?>
                <?= $this->formelement($form->get('patientId')->setValue($patient->getId()))?>
                <div class="form-group">
                    <label>Titre de consultation </label>
                    <?= $this->formelement($form->get('title'))?>
                </div>
                <div class="form-group">
                    <label>Description (remarques)</label>
                    <?= $this->formelement($form->get('description'))?>
                </div>
                <div class="text-right">
                    <button class="btn btn-primary">Ajouter</button>
                </div>

                <?= $this->form()->closeTag()?>

            </div>
        </div>
    <?php else: ?>
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-warning">Aucun patient en attente</div>
            </div>
        </div>
    <?php endif; ?>



</div>

