<div class="container">
    <div class="row">
        <div class="col-md-10">

            <h3>List des Patient</h3>

            <table class="table">

                <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <th>Address</th>
                    <th>Telephone</th>
                    <th>Genre</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->listPatient as $patient): ?>
                    <tr>
                        <td><?= $patient['lastname'] ?></td>
                        <td><?= $patient['firstname'] ?></td>
                        <td><?= $patient['gender'] ?></td>
                        <td><?= $patient['phone'] ?></td>
                        <td><?= $patient['address'] ?></td>
                        <td><a href="<?= $this->url('patient/default',['controller'=>'patient-detail']) ?>?patientId=<?= $patient['id'] ?>" class="btn btn-sm btn-info"><i class="fa fa-file-text-o"></i> details </a> </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>

            </table>


        </div>
    </div>

</div>