<div class="wrap">
    <div class="row">

        <?= $this->render($this->layout_helper('booking')); ?>


        <div class="three-fourth">
            <div class="box">
                <h2>Booking area</h2>

                <p>
                    <?php
                    $routeName = $this->routeParamsHelper();
                    echo $routeName;
                    ?>
                </p>
            </div>
        </div>

    </div>
</div>

