<aside class="one-fourth sidebar left" style="margin-top: 10px">
    <div class="widget">
        <ul class="categories">
            <li <?= $this->controllerName == 'Index' ? "class='active'" : '' ?> >
                <a href="<?= $this->url('board/booking', ['controller' => 'index', 'action' => 'index']) ?>">
                    Reservation Confirmer
                </a>
            </li>
            <li <?= $this->controllerName == 'Changepwd' ? "class='active'" : '' ?> >
                <a href="<?= $this->url('board/booking', ['controller' => 'changepwd', 'action' => 'index']) ?>">
                    Reservation Annuller
                </a>
            </li>
            <li <?= $this->controllerName == 'Photo' ? "class='active'" : '' ?> >
                <a href="<?= $this->url('board/booking', ['controller' => 'photo', 'action' => 'index']) ?>">
                    Reservation Annuller
                </a>
            </li>
        </ul>
    </div>
</aside>


