
<?php
$this->headStyle()->captureEnd();

$form = $this->registerForm;
?>

<div class="container">

    <div class="row">



        <?php
        $form->setAttribute("action", $this->url('user', ["controller" => "register", "action" => "process"]));
        $form->setAttribute("class", "form-horizontal");
        $form->prepare();
        ?>

        <?php if ($this->accountExistError): ?>
            <div class="red box">
                Account exist
            </div>
        <?php endif; ?>

        <?php if ($this->passwordError): ?>
            <div>
                les mot de passe ne sans pas les meme
            </div>
        <?php endif; ?>

        <?php if ($this->formError): ?>
            <div>
                Verfie les champs
            </div>
        <?php endif; ?>


        <!--- Content -->
        <div class="col-md-3">
            <!--Login-->
            <div class="box">


                <div class="">
                    <p>Pas encore membre ? Inscrivez-vous gratuitement</p>
                </div>
                
                <hr>
                <p>en 30 secondes avec une adresse email</p>

                <?php echo $this->form()->openTag($form); ?>

                <div class="form-group">                    
                    <label for="name">Genre</label>                    
                    <?= $this->formelement($form->get('gender')->setAttribute('class', 'form-control')); ?>
                </div>


                <div class="form-group">                    
                    <label for="name">Last name</label>
                    <?= $this->formelement($form->get('lastname')->setAttribute('class', 'form-control')); ?>                    
                </div>

                <div class="form-group">                    
                    <label for="email">First name</label>                    
                    <?= $this->formelement($form->get('firstname')->setAttribute('class', 'form-control')); ?>                    
                </div>

                <div class="form-group">                    
                    <label for="password">Your Email</label>                    
                    <?= $this->formelement($form->get('email')->setAttribute('class', 'form-control')); ?>                    
                </div>

                <div class="form-group">
                    <label for="password">Your Mobile (verification with phone)</label>                    
                    <?= $this->formelement($form->get('phone')->setAttribute('class', 'form-control')); ?>                    
                </div>


                <div class="form-group">                    
                    <label for="password2">type a password</label>                    
                    <?= $this->formelement($form->get('password')->setAttribute('class', 'form-control')); ?>                    
                </div>


                <div class="form-group">                    
                    <label for="password2">Confirm your password</label>                    
                    <?= $this->formelement($form->get('confirm_password')->setAttribute('class', 'form-control')); ?>                    
                </div>

                <div class="form-group">
                    <label for="password2">Année de naissance </label>                    
                    <?= $this->formelement($form->get('birthyear')->setAttribute('class', 'form-control')); ?>                    
                </div>
                
                <div class="form-group">                    
                    <input type="submit" value="Create an account" class="btn btn-primary">                    
                </div>

                <p>Already have an account? <a href="<?php echo $this->url('user') ?>">Login</a>.</p>
                <?= $this->form()->closeTag(); ?>
            </div>
            <!--//Login-->
        </div>
        <!--- //Content -->
    </div>
</div>