<?php

$form = $this->form;
$form->setAttributes([
   'action'=>$this->url('patient/default',['controller'=>'new', 'action'=>'process']),
    'method'=>'post'
]);
$form->prepare();

?>

<div class="container">

    <?= $this->form()->openTag($form); ?>
    <div class="row">

        <h3>Ajouter Un nouveau patient a la base de données</h3>

        <div class="col-md-6">

            <div class="form-group">
                <label>Nom </label>
                <?= $this->formelement($form->get('lastname')) ?>
                <?= $this->formElementErrors($form->get('lastname')) ?>
            </div>

            <div class="form-group">
                <label>Prenom </label>
                <?= $this->formelement($form->get('firstname')) ?>
                <?= $this->formElementErrors($form->get('firstname')) ?>
            </div>

            <div class="form-group">
                <label>Genre </label>
                <?= $this->formelement($form->get('gender')) ?>
                <?= $this->formElementErrors($form->get('gender')) ?>
            </div>

            <div class="form-group">
                <label>Année de naissance </label>
                <?= $this->formelement($form->get('birthyear')) ?>
                <?= $this->formElementErrors($form->get('birthyear')) ?>
            </div>

        </div>
        <div class="col-md-6">

            <div class="form-group">
                <label>Numero de telephone (pour contacter) </label>
                <?= $this->formelement($form->get('phone')) ?>
                <?= $this->formElementErrors($form->get('phone')) ?>
            </div>

            <div class="form-group">
                <label>Address </label>
                <?= $this->formelement($form->get('address')) ?>
                <?= $this->formElementErrors($form->get('address')) ?>
            </div>

            <div class="form-group">
                <label>Entrer le code de verification </label>
                <?= $this->formelement($form->get('captcha')) ?>
                <?= $this->formElementErrors($form->get('captcha')) ?>
            </div>
        </div>

    </div>
    <div class="gap"></div>
    <div class="text-right">
        <button class="btn btn-lg btn-primary">Ajouter</button>
    </div>
    <?php $this->form()->closeTag(); ?>

</div>
