<?php

/**
 * Generated by ZF2ModuleCreator
 */

return [


    'view_helpers' => [
    ],


    'view_manager' => [
        'template_path_stack' => [
            __DIR__ . '/../view',
        ],
        //more options
        'template_map' => [
            'layout/profile'=> __DIR__ .'/../view/layout/profile.phtml'
        ],
    ],

    'controllers' => [
        'invokables'=> [
            'Profile\Controller\Index'=>'Profile\Controller\IndexController',
            'Profile\Controller\Changepwd'=>'Profile\Controller\ChangepwdController',
            'Profile\Controller\Verification'=>'Profile\Controller\VerificationController',
            'Profile\Controller\Photo'=>'Profile\Controller\PhotoController',
            'Profile\Controller\Mycar'=>'Profile\Controller\MycarController',
        ]
    ],

    'service_manager' => [],

    'router' => [
        //Uncomment below to add routes
        'routes' => [
            'profile' => [
                'type' => 'Literal',
                'options' => [
                    'route' => '/profile',
                    'defaults' => [
                        '__NAMESPACE__' => 'Profile\Controller',
                        'controller' => 'Index',
                        'action' => 'index',
                    ]
                ]
            ]
        ],
        'may_terminate' => true,
        'child_routes' => [
            'default' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/[:controller[/:action]]',
                    'constraints' => [
                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                    ]
                ]
            ]
        ]
    ]
];